spring:

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: LINFENG ZHOU
    password: Xs!241926126
    url: jdbc:mysql://localhost:3306/springsecurity

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update